deployTarget: custom

global:
  postgresql:
    postgresqlPassword: pachyderm
    postgresqlPostgresPassword: pachyderm

pachd:
  service:
    type: ClusterIP
  image:
    tag: local
  storage:
    backend: MINIO
    minio:
      bucket: "pachyderm-test"
      endpoint: "minio.default.svc.cluster.local:9000"
      id: "minioadmin"
      secret: "minioadmin"
      secure: "false"
      signature: ""
  lokiDeploy: true
  metrics:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512M

etcd:
  resources:
    requests:
      cpu: 250m
      memory: 512M

proxy:
  enabled: true
  service:
    type: NodePort
    httpNodePort: 30650
